### ISSUE TITLE
Whether Carla0.9.14 is available in this Project or not?

### ISSUE THREAD

**Issue by 2019211753** [Derkai52/OpenCDA#2]
Thanks for you reply in advance.

**Comment by Derkai52** [comment]
Thank you for your question! Due to OpenCDA, current version support for Carla 0.9.14 is not perfect, so I do not recommend using it directly.

A more reasonable version is Carla0.9.12.

**Comment by 2019211753** [comment]
> Thank you for your question! Due to OpenCDA, current version support for Carla 0.9.14 is not perfect, so I do not recommend using it directly.
> 
> A more reasonable version is Carla0.9.12.

Thanks!
